//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by res.rc
//
#define RESETWORD                       1
#define APPENDCHAR                      2
#define DELETELASTCHAR                  3
#define INSERTWORD                      4
#define GOUP                            5
#define ID_TASK_BAR                     6
#define GODOWN                          6
#define VALIDATEFOCUS                   7
#define RACCOURCI_DISABLE               8
#define IDD_MAIN_DIALOG                 9
#define IDR_MENU_MINIMIZE               102
#define IDI_ICON_APPLICATION            103
#define IDD_DIALOG_CONFIGURER           104
#define IDD_DIALOG_DICTIONNAIRE         105
#define IDD_DIALOG_DEMARRAGE            106
#define IDI_ICON_DEMARRAGE              108
#define IDD_DIALOG_INSERTION            109
#define IDD_DIALOG_SPEECH_SYNTHESIS     112
#define IDD_DIALOG_NEW_DICO             114
#define IDD_DIALOG_DICO_NAME            115
#define IDC_BUTTON_F1                   1001
#define IDC_BUTTON_F2                   1002
#define IDC_BUTTON_APERCU               1002
#define IDC_BUTTON_F3                   1003
#define IDC_SLIDER_ROUGE                1003
#define IDC_BUTTON_F4                   1004
#define IDC_SLIDER_VERT                 1004
#define IDC_BUTTON_F5                   1005
#define IDC_SLIDER_BLEU                 1005
#define IDC_BUTTON_F6                   1006
#define IDC_EDIT_ROUGE                  1006
#define IDC_BUTTON_F7                   1007
#define IDC_EDIT_VERT                   1007
#define IDC_BUTTON_F8                   1008
#define IDC_EDIT_BLEU                   1008
#define IDC_BUTTON_F9                   1009
#define IDC_RADIO_TEXTE                 1009
#define IDC_BUTTON_F10                  1010
#define IDC_RADIO_FOND                  1010
#define IDC_CHECK_ITALIQUE              1012
#define IDC_COMBO_POLICE                1014
#define IDC_EDIT_MOT                    1015
#define IDC_BUTTON_AJOUTER              1016
#define IDC_BUTTON_NEW_DICO             1017
#define IDC_BUTTON_SUPPRIMER            1018
#define IDC_EDIT_RECHERCHER             1019
#define IDC_BUTTON_SUPPRIMER2           1019
#define IDC_BUTTON_MODIFY               1019
#define IDC_LIST_RESULTAT               1021
#define IDC_STATIC_RETOUR               1022
#define IDC_EDIT_NB_LETTRE              1025
#define IDC_EDIT_TEMPS                  1026
#define IDC_CHECK_AUTOMATIQUE           1027
#define IDC_STATIC_INSERER              1028
#define IDC_CHECK_SYNTHESIS             1028
#define IDC_RAZ_POIDS                   1029
#define IDC_BUTTON_RAZ_POIDS            1029
#define IDC_BUTTON_RAZ_DICO             1030
#define IDC_BUTTON_DELETE_DICO          1030
#define IDC_BUTTON_RAZ_MOT              1031
#define IDC_SLIDER_OPACITY              1048
#define IDC_STATIC_RED                  1049
#define IDC_STATIC_GREEN                1050
#define IDC_STATIC_BLUE                 1051
#define IDC_STATIC_NBLETTER             1052
#define IDC_STATIC_TIME                 1053
#define IDC_STATIC_TRANSPARENCY         1055
#define IDC_STATIC_COLOR                1056
#define IDC_STATIC_COLORS               1056
#define IDC_STATIC_ACCESS               1057
#define IDC_STATIC_FONT                 1058
#define IDC_STATIC_OVERVIEW             1059
#define IDC_SLIDER_NBWORD               1062
#define IDC_STATIC_NBWORD               1063
#define IDC_STATIC_TRANSPARENT          1067
#define IDC_STATIC_OPAC                 1068
#define IDC_EDIT_NBWORD                 1069
#define IDC_RADIO_FOCUS                 1070
#define IDC_CHECK_GRAS                  1071
#define IDC_RADIO_NORMAL                1076
#define IDC_STATIC_STATE                1077
#define IDC_STATIC_WORDS                1081
#define IDC_COMBO_VOICE_SELECT          1084
#define IDC_SLIDER_VOICE_VOLUME         1085
#define IDC_SLIDER_VOICE_SPEED          1086
#define IDC_CHECK_VOICE_HOVER           1087
#define IDC_CHECK_VOICE_INSERT          1088
#define IDC_STATIC_VOICE_ACTIVATION     1089
#define IDC_STATIC_VOICE_SPEED          1094
#define IDC_STATIC_VOICE_VOLUME         1095
#define IDC_STATIC_VOICE_PARAM          1096
#define IDC_BUTTON_SPEECH_SYNTHESIS     1097
#define IDC_BUTTON_VOICE_TEST           1098
#define IDC_EDIT_VOICE_VOLUME           1099
#define IDC_EDIT_VOICE_SPEED            1100
#define IDC_EDIT_VOICE_TEST             1101
#define IDC_STATIC_LOADING              1103
#define IDC_STATIC_CONF_COLOR           1104
#define IDC_STATIC_GROUP_SELECT         1105
#define IDC_CHECK_SELECT_BY_FUNCTION    1106
#define IDC_CHECK_SELECT_BY_CLIC        1107
#define IDC_CHECK_SELECT_BY_ARROWS      1108
#define IDC_STATIC_GROUP_LANG           1109
#define IDC_STATIC_GROUP_SUPPORT        1109
#define IDC_COMBO_LANG                  1110
#define IDC_LIST_DICO                   1114
#define IDC_RADIO_VIRGIN                1116
#define IDC_RADIO_FROM_DEFAULT          1117
#define IDC_RADIO_FROM_ACTUAL           1118
#define IDC_RADIO_FROM_FILE             1119
#define IDC_STATIC_NEW_DICO_CREATE      1120
#define IDC_COMBO_CHOICE_DICO           1121
#define IDC_BUTTON_LOAD_DICO            1122
#define IDC_EDIT_POIDS                  1123
#define IDC_STATIC_MANAGE_DICO          1124
#define IDC_STATIC_CHOICE_DICO          1125
#define IDC_STATIC_MANAGE_WORD          1126
#define IDC_EDIT1                       1127
#define IDC_EDIT_NEW_DICO_NAME          1127
#define IDC_STATIC_NEW_DICO_NAME        1128
#define IDC_STATIC_SUPPORT_HELP         1129
#define IDC_STATIC_SUPPORT_MAIL         1130
#define IDC_CHECK1                      1131
#define IDC_CHECK_AUTO_INSERT           1131
#define ID_POPUP_QUITTER                40003
#define ID_POPUP_DICTIONNAIRE           40005
#define ID_POPUP_CONFIGURER             40006
#define ID_Menu                         40007
#define ID_POPUP_ANNULER                40008
#define ID_POPUP_DISABLE                40011
#define IDC_LISTVIEW_DICO               50001
#define PM_AFFICHERRECHERCHE			1001
#define PM_AUTOINSERT					1002
#define PM_NAME_OK						1003
#define PM_CREATE_OK					1004
#define PM_FILLDICOCOMBO				1005


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         40013
#define _APS_NEXT_CONTROL_VALUE         1132
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
